'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Referencia1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Referencia1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As Referencia1.HelloWorldRequest) As Referencia1.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As Referencia1.HelloWorldRequest) As System.Threading.Tasks.Task(Of Referencia1.HelloWorldResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suma", ReplyAction:="*")>  _
        Function suma(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/suma", ReplyAction:="*")>  _
        Function sumaAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resta", ReplyAction:="*")>  _
        Function resta(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/resta", ReplyAction:="*")>  _
        Function restaAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/producto", ReplyAction:="*")>  _
        Function producto(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/producto", ReplyAction:="*")>  _
        Function productoAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/division", ReplyAction:="*")>  _
        Function division(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/division", ReplyAction:="*")>  _
        Function divisionAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Referencia1.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Referencia1.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Referencia1.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Referencia1.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits Referencia1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of Referencia1.WebService1Soap)
        Implements Referencia1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Referencia1_WebService1Soap_HelloWorld(ByVal request As Referencia1.HelloWorldRequest) As Referencia1.HelloWorldResponse Implements Referencia1.WebService1Soap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As Referencia1.HelloWorldRequest = New Referencia1.HelloWorldRequest()
            inValue.Body = New Referencia1.HelloWorldRequestBody()
            Dim retVal As Referencia1.HelloWorldResponse = CType(Me,Referencia1.WebService1Soap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Referencia1_WebService1Soap_HelloWorldAsync(ByVal request As Referencia1.HelloWorldRequest) As System.Threading.Tasks.Task(Of Referencia1.HelloWorldResponse) Implements Referencia1.WebService1Soap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of Referencia1.HelloWorldResponse)
            Dim inValue As Referencia1.HelloWorldRequest = New Referencia1.HelloWorldRequest()
            inValue.Body = New Referencia1.HelloWorldRequestBody()
            Return CType(Me,Referencia1.WebService1Soap).HelloWorldAsync(inValue)
        End Function
        
        Public Function suma(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal Implements Referencia1.WebService1Soap.suma
            Return MyBase.Channel.suma(valor1, valor2)
        End Function
        
        Public Function sumaAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal) Implements Referencia1.WebService1Soap.sumaAsync
            Return MyBase.Channel.sumaAsync(valor1, valor2)
        End Function
        
        Public Function resta(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal Implements Referencia1.WebService1Soap.resta
            Return MyBase.Channel.resta(valor1, valor2)
        End Function
        
        Public Function restaAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal) Implements Referencia1.WebService1Soap.restaAsync
            Return MyBase.Channel.restaAsync(valor1, valor2)
        End Function
        
        Public Function producto(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal Implements Referencia1.WebService1Soap.producto
            Return MyBase.Channel.producto(valor1, valor2)
        End Function
        
        Public Function productoAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal) Implements Referencia1.WebService1Soap.productoAsync
            Return MyBase.Channel.productoAsync(valor1, valor2)
        End Function
        
        Public Function division(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As Decimal Implements Referencia1.WebService1Soap.division
            Return MyBase.Channel.division(valor1, valor2)
        End Function
        
        Public Function divisionAsync(ByVal valor1 As Decimal, ByVal valor2 As Decimal) As System.Threading.Tasks.Task(Of Decimal) Implements Referencia1.WebService1Soap.divisionAsync
            Return MyBase.Channel.divisionAsync(valor1, valor2)
        End Function
    End Class
End Namespace
